export const INCREMENT_SCORE = 'INCREMENT_SCORE';
export const RESET_SCORE = 'RESET_SCORE';
export const SET_NAME = 'SET_NAME';
export const RESET_NAME = 'RESET_NAME';
export const SET_GAMESTATE = 'SET_GAMESTATE';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const SET_QUESTION_ANSWERED = 'SET_QUESTION_ANSWERED';
export const RESET_GAME = 'RESET_GAME';