export const INCREMENTSCORE = 'INCREMENTSCORE';
export const RESETSCORE = 'RESETSCORE';
export const SETNAME = 'SETNAME';
export const RESETNAME = 'RESETNAME';
export const SETGAMESTATE = 'SETGAMESTATE';
export const NEXTQUESTION = 'NEXTQUESTION'